In [0]:
import numpy as np


In [0]:
a=np.array([3,3,4,5,6,7,8])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([1,2,3,4,5,4,5])

In [0]:
b

array([1, 2, 3, 4, 5, 4, 5])

In [0]:
a+b

array([ 4,  5,  7,  9, 11, 11, 13])

In [0]:
a*2

array([ 6,  6,  8, 10, 12, 14, 16])

In [0]:
a**2

array([ 9,  9, 16, 25, 36, 49, 64])

In [0]:
c=a[3]+b[2]

In [0]:
c

8

In [0]:
# Double dimensional array
d = np.array([[1,2,3],[4,5,6]])   # 2x3 matrix 2 row 3 col


In [52]:
d
df=d.reshape(3,2)   # Reshape to convert 2x3 to 3x2
df

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
y=d+5

In [0]:
cube = d**3
cube

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [0]:
z = np.array([[2,7],[3,8],[2,9],[9,4] ])
z.shape
z


array([[2, 7],
       [3, 8],
       [2, 9],
       [9, 4]])

In [36]:
# x[row range, column range]

z[0:2]   # 3rd row will be excluded
z[0:]    # All rows
z[0:,0]
z[0:2,0]
d[0:,0:2]
# skiping the column order
d[0:,[0,2]]   # only col 0 and 2 needed then write index no of col in list
d[[0,1]]
z[[0,3],1]

p = np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])
p

array([[1, 9, 7],
       [3, 2, 8],
       [4, 5, 6],
       [2, 9, 0]])

In [47]:
p[1:,0]
p[1:,[0,2]]

array([[3, 8],
       [4, 6],
       [2, 0]])

In [0]:
''' Task : 
Rows and col from user 
16 32 
4x4  8x4 or .... what all combination possible 2x2 4x4 print them 

2 === Generate 3x2 and 2x5 2d array with random elements and save this data into two separate data
Read data from file and make 3x2 into 2x3

slashlinuxcode.blogspot.com --numpy deep dive'''
ty = np.zeros((3,6))
ty 
tyu = np.ones((3,4))
tyu
tyui = np.full((4,5),9)
tyui
for i in dir(np):
  if 'zer' in i:
    print(i)
    
[i  for i in dir(np)  if 'zer' in i]
